### PR TITLE
Add CITATION file and startup messages

### PR DESCRIPTION
**Pull request by bpbond**

### CODE REVIEW

**Comment by bpbond** [comment]
@stephpenn1 Any review?

**Comment by stephpenn1** [comment]
Totally missed this, sorry.

**Comment by stephpenn1** [comment]
Changed color ranges, but I can't get the `labels = comma` argument to work for the lat figure

**Comment by bpbond** [comment]
Lovely! OK to merge?

**Comment by stephpenn1** [comment]
Yes, all clear!

**Pull request merged**
