### PR TITLE
Contributor data fixes

### LINKED ISSUE #152: Email bounceback and flipped first/family names
From quazhang - find and fix/remove. In addition @stephpenn1 notes some names are mixed up.

### PR DESCRIPTION
**Pull request by stephpenn1**
Resolves #152

### CODE REVIEW

**Comment by bpbond** [comment]
# [Codecov](https://codecov.io/gh/bpbond/cosore/pull/155?src=pr&el=h1) Report
> Merging [#155](https://codecov.io/gh/bpbond/cosore/pull/155?src=pr&el=desc) into [master](https://codecov.io/gh/bpbond/cosore/commit/691df8224de27b42b3f8dc972801154e7f867f98&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/bpbond/cosore/pull/155?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master     #155   +/-   ##
=======================================
  Coverage   94.08%   94.08%           
=======================================
  Files           8        8           
  Lines         676      676           
=======================================
  Hits          636      636           
  Misses         40       40           
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/bpbond/cosore/pull/155?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/bpbond/cosore/pull/155?src=pr&el=footer). Last update [691df82...ee09ff0](https://codecov.io/gh/bpbond/cosore/pull/155?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by bpbond** [comment]
Thanks @stephpenn1 !

**Comment by stephpenn1** [comment]
What was the coverage error?

**Comment by bpbond** [comment]
Oh good question. If you look at the [coverage report](https://codecov.io/gh/bpbond/cosore/pull/155/diff) you'll see that one of the `stop()` commands I modified isn't currently covered by our tests. (Didn't realize that.) And because my PR didn't fix this, it 'errored'. But this isn't a big deal, so I just merged.

Basic principle–any new code we add should be covered by tests as much as possible.

**Pull request merged**
