### PR TITLE
ESSD figures

### PR DESCRIPTION
**Pull request by stephpenn1**
Two options for fig 1 (map):
image

image

Beginning skeleton for fig 2:
image

### CODE REVIEW

**Comment by bpbond** [comment]
Here's my code for the leaflet map:
```R
# library(ggplot2)
# library(ggmap)
library(dplyr)
# library(mapdata)

library(leaflet)

x <- read.csv("/Users/d3x290/Dropbox/Documents/Work/Data-ongoing/Soil respiration database/github/srdb/srdb-data.csv")

#mp <- get_map(maptype = "terrain-background")

# Load the library
library(leaflet)

# Note: if you do not already installed it, install it with:
# install.packages("leaflet")

# Background 1: NASA
# m <- leaflet() %>% 
#   addTiles() %>% 
#   setView( lng = 2.34, lat = 48.85, zoom = 5 ) %>% 
#   addProviderTiles("NASAGIBS.ViirsEarthAtNight2012")
# m

df <- data.frame(lon = x$Longitude, lat = x$Latitude, Rh_annual = x$Rh_annual)
df <- subset(df, !is.na(lon) & !is.na(lat))
df_rh <- subset(df, !is.na(Rh_annual))

library(cosore)
csr <- csr_datbase()

# Background 2: World Imagery
m <- leaflet() %>% 
  addProviderTiles("Esri.WorldImagery") %>% 
  addCircleMarkers(lng = df_rh$lon, lat = df_rh$lat, radius = 0.5, color = "red") %>% 
  addCircleMarkers(lng = csr$CSR_LONGITUDE, lat = csr$CSR_LATITUDE)
```

**Comment by bpbond** [comment]
By the way @stephpenn1 for figure 2 I was thinking something more like this

Screen Shot 2020-03-23 at 11 58 55 AM

**Comment by stephpenn1** [comment]
@bpbond so, you would like more temporal coverage displayed?

**Comment by bpbond** [comment]
The plot I put up is data density within months over time. There are other ways to do it, and other things to visualize...not sure. Could have data density by latitude, for example.

**Comment by bpbond** [comment]
@stephpenn1 Can we touch base about this on Tuesday?

**Comment by stephpenn1** [comment]
Yes

**Comment by stephpenn1** [comment]
Other options to discuss Tuesday (these are rough):
image

I do like your idea by latitude
image

I do like the idea of showing the data by latitude, will come up with a graph for that as well

**Comment by bpbond** [comment]
Wow!!!!!!!!! That waffle chart is gorgeous. 😍

**Comment by stephpenn1** [comment]
Fig 3: 
image

still need to reorder the y axis so [-35,-30] is at the bottom, but theres a comment in the code to go back to it later

**Comment by stephpenn1** [comment]
And updated Fig 1.
image

**Comment by stephpenn1** [comment]
Note: most recent updates have been pushed and ready to merge if accepted

**Comment by bpbond** [comment]
👏 those look great!

So, figure 1 the map; figure 2 the waffle plot; and figure 3 the latitude one? Sounds good.

**Pull request merged**
